# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunden',
            fields=[
                ('Kunden_ID', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Kommentar', models.CharField(max_length=1000)),
                ('Telefon', models.IntegerField(max_length=100)),
                ('eMail', models.CharField(max_length=100)),
                ('Kontoinhaber', models.CharField(max_length=100)),
                ('Kontonummer', models.CharField(max_length=100)),
                ('BLZ', models.IntegerField(max_length=100)),
                ('Bank', models.CharField(max_length=100)),
            ],
        ),
    ]
