# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worefApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunden',
            name='BLZ',
        ),
        migrations.RemoveField(
            model_name='kunden',
            name='Telefon',
        ),
        migrations.AlterField(
            model_name='kunden',
            name='Kunden_ID',
            field=models.AutoField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
