# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worefApp', '0002_auto_20171029_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='kunden',
            name='Actung',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='kunden',
            name='BLZ',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kunden',
            name='Telefon',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='kunden',
            name='en',
            field=models.BooleanField(default=0),
        ),
    ]
