# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worefApp', '0004_auto_20171029_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referanten',
            fields=[
                ('ID', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('EintrittsDatum', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Activ', models.BooleanField(default=0)),
                ('Schluessel', models.BooleanField(default=0)),
            ],
        ),
    ]
