# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worefApp', '0005_referanten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referanten',
            name='EintrittsDatum',
            field=models.DateField(auto_now_add=True),
        ),
    ]
